services:
  - type: web
    name: gerador-imagem-ia
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CF_ACCOUNT_ID
        sync: false
      - key: CF_API_TOKEN
        sync: false
      - key: CF_MODEL
        value: "@cf/black-forest-labs/flux-2-klein-4b"
      - key: HF_TOKEN
        sync: false
      - key: HF_MODEL
        value: black-forest-labs/FLUX.1-schnell
